### PR TITLE
Fill out sbd-o-bahn-server-tester into initial broad test suite

### PR DESCRIPTION
**Pull request by neonphog**
RESOLVES https://github.com/holochain/sbd/issues/28

Adds tests to the test suite.

Anyone reviewing, please let me know any additional tests you'd like to see in here.

### CODE REVIEW

**Review by ThetaSinner — APPROVED** [review]
Code looks good as far as I can tell.

Is there a test demonstrating that messages are kept separate? I.e. 4 agents, two senders and two receivers, interleaving the sends and making sure the receivers only get the messages they're supposed to see.

Otherwise the test scenarios look reasonable to me and we can add more as needed.

The test names are useful but a short comment describing what each test is doing and why might be useful?

**Comment by neonphog** [comment]
> Is there a test demonstrating that messages are kept separate? I.e. 4 agents, two senders and two receivers, interleaving the sends and making sure the receivers only get the messages they're supposed to see.

Good idea, will add :+1:

**Comment by neonphog** [comment]
> a short comment describing what each test is doing

Good idea, will add :+1:

**Review by jost-s — APPROVED** [review]
LGTM
Should there be a test/behavior for DoS attacks?

**Comment by neonphog** [comment]
> Should there be a test/behavior for DoS attacks?

It's good to consider this. I've landed on: no. This is one of the benefits of using cloudflare itself. They should auto-block bad actors that are engaged in attacks when they can identify them, and the system is destributed, that is the durable objects (one for each peer connection) are all running on edge systems, so it'd be very hard to attack them all at once.

**Pull request merged**
